# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The Powerful Influence of Literature on Cinema ?
email: mallory.henriet@epfl.ch
description: >- # this means to ignore newlines until "baseurl:"
  We will use several questions to drive our analysis : First, we will analyze What kind of books are adapted to movies? How do they differ from unadapted movies ? This is done through analyzing the most adapted time periods and authors book-wise, and through crossing information by analyzing the adaptation languages, genres and financing countries. This should lead us to understand which trends underline book’s adaptation through time and across countries.
  Then, we will analyze the success of the adaptations themselves: are they more successful than non-adaptations? Is there a correlation between the success of a book and of its adaptation? This success can both be represented in terms of box-office, rating and engagement (number of reviews).
  Finally, we will analyze Does a book’s plots and its adaptation’s plot resemble each other? This would lead us to understand to what extent are the subjects in the plots the same, or if adaptations tend to add / remove some topics. We could then understand how this correlates with the rating of users.
baseurl: "/ada-2024-project-padamalgame/docs" # the subpath of your site, e.g. /blog
url: "https://epfl-ada.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: MalloryHenriet

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
